export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  UNPROCESSABLE_ENTITY: 422,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
} as const;

export default HTTP_STATUS;
